---

# Documentation:
# This playbook is used to deploy an AMQ Streams cluster plus an IoT demo
#
#
- name:               Create kafka demo
  hosts:              localhost
  connection:         local
  gather_facts: no

  vars_prompt:
    - name:           clone_destination
      prompt:         "Please Enter the local destination to store the required files"
      default:        /tmp/ocpdemotmp
      private:        no


  tasks:

    - name: Clone base git repo from https://github.com/jonmwalton/ocp-demo-setup.git
      git:
        repo: https://github.com/jonmwalton/ocp-demo-setup.git
        dest: "{{clone_destination}}"
        version: master
        update: yes
        clone: yes
        force: yes


    - name: Clone kafka operator repo
      git:
        repo: https://github.com/strimzi/strimzi-kafka-operator.git
        dest: "{{clone_destination}}/amq-streams"
        version: master
        update: yes
        clone: yes
        force: yes


#####################################################
# Create AMQ Streams Cluster project
#####################################################
    - name:           Create AMQ Streams Cluster project
      k8s:
        api_version:  v1
        verify_ssl:   no
        kind:         Project
        name:         amq-streams-cluster
        state:        present

#####################################################
# Create all kafka cluster artefacts
#####################################################
    - name: Modify install files
      shell: oc get project amq-streams-cluster

    - name: Modify install files
      shell: "sed -i 's/namespace: .*/namespace: amq-streams-cluster/' {{clone_destination}}/amq-streams/install/cluster-operator/*RoleBinding*.yaml"

    - name: Install cluster operator
      shell: oc apply -f {{clone_destination}}/amq-streams/install/cluster-operator -n amq-streams-cluster

    - name: Install templates
      shell: oc apply -f {{clone_destination}}/amq-streams/examples/templates/cluster-operator -n amq-streams-cluster

    - name: Create kafka ephemeral
      k8s:
        src: '{{clone_destination}}/amq-streams/examples/kafka/kafka-ephemeral.yaml'
        state:  present
        namespace:  amq-streams-cluster

    - name: Create kafka connect
      k8s:
        src: '{{clone_destination}}/amq-streams/examples/kafka-connect/kafka-connect.yaml'
        state:  present
        namespace:  amq-streams-cluster        


    - name: Clone IoT kafka demo repo
      git:
        repo: https://github.com/strimzi/strimzi-lab.git
        dest: "{{clone_destination}}/amq-streams"
        version: master
        update: yes
        clone: yes
        force: yes

    - name: Modify kafka bootstrap URL
      shell: "sed -i 's/my-cluster-kafka:9092/my-cluster-kafka-bootstrap.amq-streams-cluster:9092/' {{clone_destination}}/amq-streams/iot-demo/consumer-app/resources/consumer-app.yml"
    
    - name: Modify kafka bootstrap URL
      shell: "sed -i 's/my-cluster-kafka:9092/my-cluster-kafka-bootstrap.amq-streams-cluster:9092/' {{clone_destination}}/amq-streams/iot-demo/device-app/resources/device-app.yml"

    - name: Modify kafka bootstrap URL
      shell: "sed -i 's/my-cluster-kafka:9092/my-cluster-kafka-bootstrap.amq-streams-cluster:9092/' {{clone_destination}}/amq-streams/iot-demo/stream-app/resources/stream-app.yml"

    - name: Modify kafka bootstrap URL
      shell: "sed -i 's/ConfigMap/KafkaTopic/' {{clone_destination}}/amq-streams/iot-demo/stream-app/resources/topics.yml"

    - name: Modify kafka bootstrap URL
      shell: "sed -i 's/v1/v1alpha1/' {{clone_destination}}/amq-streams/iot-demo/stream-app/resources/topics.yml"      

    - name: Create Topics
      k8s:
        src: '{{clone_destination}}/amq-streams/iot-demo/stream-app/resources/topics.yml'
        state:  present
        namespace:  amq-streams-cluster

#####################################################
# Create IoT demo project
#####################################################
    - name:           Create IoT Demo project
      k8s:
        api_version:  v1
        verify_ssl:   no
        kind:         Project
        name:         iot-kafka-demo
        state:        present

    - name: Join the IoT demo project to the Kafka Cluster project
      shell: oc adm pod-network join-projects --to=iot-kafka-demo amq-streams-cluster

    - name: Create stream app
      k8s:
        src: '{{clone_destination}}/amq-streams/iot-demo/stream-app/resources/stream-app.yml'
        state:  present
        namespace:  iot-kafka-demo

    - name: Create device app
      k8s:
        src: '{{clone_destination}}/amq-streams/iot-demo/device-app/resources/device-app.yml'
        state:  present
        namespace:  iot-kafka-demo

    - name: Create consumer app
      k8s:
        src: '{{clone_destination}}/amq-streams/iot-demo/consumer-app/resources/consumer-app.yml'
        state:  present
        namespace:  iot-kafka-demo

    - name: Remove git folder (cleanup)
      file:
        path: "{{clone_destination}}"
        state: absent